package constants

// ERROR constants
const (
	// general
	OK                = "OK"
	ERROR_INTERNAL    = "INTERNAL_ERROR"
	ERROR_BAD_REQUEST = "BAD_REQUEST"
	ERROR_NOT_FOUND   = "NOT_FOUND"
	INVALID_ACTION    = "INVALID_ACTION"

	// order
	ERROR_ORDER_NOT_FOUND             = "ERROR_ORDER_NOT_FOUND"
	ERROR_ORDER_DTO_CONVERT           = "ERROR_DTO_CONVERT"
	ERROR_ORDER_CREATE_FAILED         = "ERROR_ORDER_CREATE_FAILED"
	ERROR_ORDER_UPDATE_FAILED         = "ERROR_ORDER_UPDATE_FAILED"
	ERROR_ORDER_CANCEL_FAILED         = "ERROR_ORDER_CANCEL_FAILED"
	ERROR_ORDER_CANCEL_INVALID_STATUS = "ERROR_ORDER_CANCEL_INVALID_STATUS"
)

// LOG event constants
const (
	ORDER_CREATED   = "ORDER_CREATED"
	ORDER_CANCELLED = "ORDER_CANCELLED"
)
