### health check
GET http://{{$dotenv ORDER_SERVICE_HOST}}:{{$dotenv ORDER_SERVICE_PORT}}/ping HTTP/1.1

### create new order
POST http://{{$dotenv ORDER_SERVICE_HOST}}:{{$dotenv ORDER_SERVICE_PORT}}/orders HTTP/1.1
content-type: application/json

{
    "user_id": "{{$guid}}"
}

### get order detail
@order_id=127
GET http://{{$dotenv ORDER_SERVICE_HOST}}:{{$dotenv ORDER_SERVICE_PORT}}/orders/{{order_id}} HTTP/1.1
content-type: application/json
