spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  kafka:
    listener:
      ack-mode: MANUAL # otherwise enable-auto-commit = false still commit offsets
      type: batch
    consumer:
      bootstrap-servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:29093}"
      auto-offset-reset: earliest # read from beginning
      enable-auto-commit: false
      allow-auto-create-topics: false
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
  liquibase:
    change-log: classpath:database/migration/db.changelog-master.yml
    enabled: true
    default-schema: checkout_schema
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
  #  data:
  #    redis:
  #      host: localhost
  #      port: 6379
  jackson:
    default-property-inclusion: NON_NULL
  task:
    scheduling:
      pool:
        size: 10
  allowed-origins: "*"
  #  cloud:
  #    openfeign:
  #      okhttp:
  #        enabled: true
  #      client:
  #        config:
  #          default:
  #            connectTimeout: 60000
  #            readTimeout: 120000
  #            loggerLevel: full
  #          dummyFeignClient:
  #            connectTimeout: 3000
  #            readTimeout: 3000
  #            loggerLevel: full
  #      micrometer:
  #        enabled: false
  lifecycle:
    timeout-per-shutdown-phase: 60s
server:
  shutdown: graceful
  port: ${CHECKOUT_SERVICE_PORT:8085}
#springdoc:
#  override-with-generic-response: false
#  api-docs:
#    enabled: true
#  swagger-ui:
#    config-url: /v3/api-docs/swagger-config
#    url: /v3/api-docs
#    enabled: true
#logging:
#  config: classpath:logback-spring-local.xml
#  level:
#    root: INFO
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#        cache:
