spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saga_playground
#    username: 123
#    password: 123
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace