spring:
  profiles:
    active: local
  main:
    banner-mode: "off"
  kafka:
    bootstrap-servers: "${KAFKA_HOST:localhost}:${KAFKA_PORT:29093}"
    listener:
      ack-mode: MANUAL # otherwise enable-auto-commit = false still commit offsets
      type: batch
      properties:
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
  liquibase:
    change-log: classpath:database/migration/db.changelog-master.yml
    enabled: true
    default-schema: checkout_schema
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
  jpa:
    show-sql: false # true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        type: trace
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    open-in-view: false
  jackson:
    default-property-inclusion: NON_NULL
  task:
    scheduling:
      pool:
        size: 10
  allowed-origins: "*"
  lifecycle:
    timeout-per-shutdown-phase: 60s
server:
  shutdown: graceful
  port: ${CHECKOUT_SERVICE_PORT:8085}
zookeeper:
  port: ${ZOOKEEPER_CLIENT_PORT:2181}
  host: ${ZOOKEEPER_HOST:localhost}
worker:
  checkout:
    interval: 5000 # milliseconds
grpc:
  client:
    order-service:
      address: ${ORDER_SERVICE_GRPC_ENDPOINT:static://localhost:8081}
# only enable in development process
#logging:
#  level:
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: TRACE
