CREATE TYPE "checkout_status" AS ENUM (
  'INIT',
  'PROCESSING',
  'FINALIZED',
  'FAILED'
);

CREATE TABLE "checkout" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar UNIQUE NOT NULL,
  "user_id" varchar NOT NULL,
  "checkout_session_id" varchar,
  "status" checkout_status NOT NULL,
  "amount" decimal(10,2) NOT NULL,
  "webhook_payload" json,
  "event_published" bool NOT NULL DEFAULT false,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

COMMENT ON COLUMN "checkout"."user_id" IS 'ref only';

COMMENT ON COLUMN "checkout"."event_published" IS 'for transactional outbox';