CREATE TABLE "t_inbox_order" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar UNIQUE NOT NULL,
  "payload" json NOT NULL,
  "created_at" timestamptz DEFAULT 'now()',
  "updated_at" timestamptz DEFAULT 'now()'
);

COMMENT ON COLUMN "t_inbox_order"."order_id" IS 'for msg deduplication, upsert';

COMMENT ON COLUMN "t_inbox_order"."payload" IS 'full playload of the msg it can pull from kafka';