// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.29.3

package com.saga.playground.checkoutservice.grpc.protobufs;

public final class OrderOuterClass {
  private OrderOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      OrderOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Order_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Order_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchToPendingPaymentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SwitchToPendingPaymentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SwitchToPendingPaymentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SwitchToPendingPaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\"#\n\005Order\022\n\n\002id\030\001 \001(\005\022\016\n\006st" +
      "atus\030\002 \001(\t\"+\n\035SwitchToPendingPaymentRequ" +
      "est\022\n\n\002id\030\001 \001(\005\"7\n\036SwitchToPendingPaymen" +
      "tResponse\022\025\n\005order\030\001 \001(\0132\006.Order2n\n\014Orde" +
      "rService\022^\n\033SwitchOrderToPendingPayment\022" +
      "\036.SwitchToPendingPaymentRequest\032\037.Switch" +
      "ToPendingPaymentResponseB<\n2com.saga.pla" +
      "yground.checkoutservice.grpc.protobufsP\001" +
      "Z\004./pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Order_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Order_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Order_descriptor,
        new java.lang.String[] { "Id", "Status", });
    internal_static_SwitchToPendingPaymentRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SwitchToPendingPaymentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SwitchToPendingPaymentRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_SwitchToPendingPaymentResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SwitchToPendingPaymentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SwitchToPendingPaymentResponse_descriptor,
        new java.lang.String[] { "Order", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
