// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.29.3

package com.saga.playground.checkoutservice.grpc.protobufs;

/**
 * Protobuf type {@code SwitchToPendingPaymentResponse}
 */
public final class SwitchToPendingPaymentResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:SwitchToPendingPaymentResponse)
    SwitchToPendingPaymentResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      SwitchToPendingPaymentResponse.class.getName());
  }
  // Use SwitchToPendingPaymentResponse.newBuilder() to construct.
  private SwitchToPendingPaymentResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SwitchToPendingPaymentResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.saga.playground.checkoutservice.grpc.protobufs.OrderOuterClass.internal_static_SwitchToPendingPaymentResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.saga.playground.checkoutservice.grpc.protobufs.OrderOuterClass.internal_static_SwitchToPendingPaymentResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.class, com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ORDER_FIELD_NUMBER = 1;
  private com.saga.playground.checkoutservice.grpc.protobufs.Order order_;
  /**
   * <pre>
   * return the updated order
   * </pre>
   *
   * <code>.Order order = 1;</code>
   * @return Whether the order field is set.
   */
  @java.lang.Override
  public boolean hasOrder() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * return the updated order
   * </pre>
   *
   * <code>.Order order = 1;</code>
   * @return The order.
   */
  @java.lang.Override
  public com.saga.playground.checkoutservice.grpc.protobufs.Order getOrder() {
    return order_ == null ? com.saga.playground.checkoutservice.grpc.protobufs.Order.getDefaultInstance() : order_;
  }
  /**
   * <pre>
   * return the updated order
   * </pre>
   *
   * <code>.Order order = 1;</code>
   */
  @java.lang.Override
  public com.saga.playground.checkoutservice.grpc.protobufs.OrderOrBuilder getOrderOrBuilder() {
    return order_ == null ? com.saga.playground.checkoutservice.grpc.protobufs.Order.getDefaultInstance() : order_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getOrder());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOrder());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse)) {
      return super.equals(obj);
    }
    com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse other = (com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse) obj;

    if (hasOrder() != other.hasOrder()) return false;
    if (hasOrder()) {
      if (!getOrder()
          .equals(other.getOrder())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOrder()) {
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + getOrder().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SwitchToPendingPaymentResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SwitchToPendingPaymentResponse)
      com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.saga.playground.checkoutservice.grpc.protobufs.OrderOuterClass.internal_static_SwitchToPendingPaymentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.saga.playground.checkoutservice.grpc.protobufs.OrderOuterClass.internal_static_SwitchToPendingPaymentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.class, com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.Builder.class);
    }

    // Construct using com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getOrderFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      order_ = null;
      if (orderBuilder_ != null) {
        orderBuilder_.dispose();
        orderBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.saga.playground.checkoutservice.grpc.protobufs.OrderOuterClass.internal_static_SwitchToPendingPaymentResponse_descriptor;
    }

    @java.lang.Override
    public com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse getDefaultInstanceForType() {
      return com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse build() {
      com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse buildPartial() {
      com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse result = new com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.order_ = orderBuilder_ == null
            ? order_
            : orderBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse) {
        return mergeFrom((com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse other) {
      if (other == com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse.getDefaultInstance()) return this;
      if (other.hasOrder()) {
        mergeOrder(other.getOrder());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getOrderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.saga.playground.checkoutservice.grpc.protobufs.Order order_;
    private com.google.protobuf.SingleFieldBuilder<
        com.saga.playground.checkoutservice.grpc.protobufs.Order, com.saga.playground.checkoutservice.grpc.protobufs.Order.Builder, com.saga.playground.checkoutservice.grpc.protobufs.OrderOrBuilder> orderBuilder_;
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     * @return Whether the order field is set.
     */
    public boolean hasOrder() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     * @return The order.
     */
    public com.saga.playground.checkoutservice.grpc.protobufs.Order getOrder() {
      if (orderBuilder_ == null) {
        return order_ == null ? com.saga.playground.checkoutservice.grpc.protobufs.Order.getDefaultInstance() : order_;
      } else {
        return orderBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    public Builder setOrder(com.saga.playground.checkoutservice.grpc.protobufs.Order value) {
      if (orderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        order_ = value;
      } else {
        orderBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    public Builder setOrder(
        com.saga.playground.checkoutservice.grpc.protobufs.Order.Builder builderForValue) {
      if (orderBuilder_ == null) {
        order_ = builderForValue.build();
      } else {
        orderBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    public Builder mergeOrder(com.saga.playground.checkoutservice.grpc.protobufs.Order value) {
      if (orderBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          order_ != null &&
          order_ != com.saga.playground.checkoutservice.grpc.protobufs.Order.getDefaultInstance()) {
          getOrderBuilder().mergeFrom(value);
        } else {
          order_ = value;
        }
      } else {
        orderBuilder_.mergeFrom(value);
      }
      if (order_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    public Builder clearOrder() {
      bitField0_ = (bitField0_ & ~0x00000001);
      order_ = null;
      if (orderBuilder_ != null) {
        orderBuilder_.dispose();
        orderBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    public com.saga.playground.checkoutservice.grpc.protobufs.Order.Builder getOrderBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getOrderFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    public com.saga.playground.checkoutservice.grpc.protobufs.OrderOrBuilder getOrderOrBuilder() {
      if (orderBuilder_ != null) {
        return orderBuilder_.getMessageOrBuilder();
      } else {
        return order_ == null ?
            com.saga.playground.checkoutservice.grpc.protobufs.Order.getDefaultInstance() : order_;
      }
    }
    /**
     * <pre>
     * return the updated order
     * </pre>
     *
     * <code>.Order order = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.saga.playground.checkoutservice.grpc.protobufs.Order, com.saga.playground.checkoutservice.grpc.protobufs.Order.Builder, com.saga.playground.checkoutservice.grpc.protobufs.OrderOrBuilder> 
        getOrderFieldBuilder() {
      if (orderBuilder_ == null) {
        orderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.saga.playground.checkoutservice.grpc.protobufs.Order, com.saga.playground.checkoutservice.grpc.protobufs.Order.Builder, com.saga.playground.checkoutservice.grpc.protobufs.OrderOrBuilder>(
                getOrder(),
                getParentForChildren(),
                isClean());
        order_ = null;
      }
      return orderBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:SwitchToPendingPaymentResponse)
  }

  // @@protoc_insertion_point(class_scope:SwitchToPendingPaymentResponse)
  private static final com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse();
  }

  public static com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SwitchToPendingPaymentResponse>
      PARSER = new com.google.protobuf.AbstractParser<SwitchToPendingPaymentResponse>() {
    @java.lang.Override
    public SwitchToPendingPaymentResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SwitchToPendingPaymentResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SwitchToPendingPaymentResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.saga.playground.checkoutservice.grpc.protobufs.SwitchToPendingPaymentResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

