// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.29.3

package com.saga.playground.checkoutservice.grpc.protobufs;

public interface SwitchToPendingPaymentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SwitchToPendingPaymentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * return the updated order
   * </pre>
   *
   * <code>.Order order = 1;</code>
   * @return Whether the order field is set.
   */
  boolean hasOrder();
  /**
   * <pre>
   * return the updated order
   * </pre>
   *
   * <code>.Order order = 1;</code>
   * @return The order.
   */
  com.saga.playground.checkoutservice.grpc.protobufs.Order getOrder();
  /**
   * <pre>
   * return the updated order
   * </pre>
   *
   * <code>.Order order = 1;</code>
   */
  com.saga.playground.checkoutservice.grpc.protobufs.OrderOrBuilder getOrderOrBuilder();
}
