name: Order service image CI
on: push

permissions:
  pull-requests: write
  id-token: write
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TARGET_PLATFORM: linux/arm64 # container running in macos M1 machine

jobs:
  build:
    name: Build image and publish to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     buildkitd-flags: "--debug"
      #     use: true
      #     driver: docker-container
      #     platforms: ${{ env.TARGET_PLATFORM }}
      #     driver-opts: |
      #       memory=6GiB
      #       cpu-quota=4
      #       cpuset-cpus=4

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: services/order/
      #     platforms: ${{ env.TARGET_PLATFORM }}
      #     push: true
      #     allow: |
      #       network.host
      #     tags: |
      #       ghcr.io/trungtho/saga-playground/order-service:test
      #       ghcr.io/trungtho/saga-playground/order-service:latest
      - name: Build and push image
        run: |
          docker buildx build --push -t ghcr.io/trungtho/saga-playground/order-service:test ./services/order
