name: Order service image CI
on: push

permissions:
  pull-requests: write
  id-token: write
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TARGET_PLATFORM: linux/arm64 # container running in macos M1 machine

#todo: semver integration

jobs:
  build:
    name: Build image and publish to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker buildx build --push \
            -t ghcr.io/trungtho/saga-playground/order-service:${GITHUB_SHA::7} \
            -t ghcr.io/trungtho/saga-playground/order-service:latest \
            ./services/order
