name: Order service image CI
on: push

permissions:
  pull-requests: write
  id-token: write
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build image and publish to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build image
        id: build-image
        working-directory: services/order
        run: docker build --load -t order-service:test .

      - name: Log in to the GHCR registry
        id: login-registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        run: |
          docker tag order-service:test ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/test
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/test
