name: Order service image CI
on: push

permissions:
  pull-requests: write
  id-token: write
  contents: write
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TARGET_PLATFORM: linux/arm64 # container running in macos M1 machine

jobs:
  build:
    name: Build image and publish to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        # https://github.com/docker/setup-buildx-action?tab=readme-ov-file#usage
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: "docker-container"
          use: true
          platforms: ${{ env.TARGET_PLATFORM }}
          driver-opts: |
            memory=4GiB

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.TARGET_PLATFORM }}
          context: services/order/
          push: true
          tags: |
            ghcr.io/trungtho/saga-playground/hihi:test
            ghcr.io/trungtho/saga-playground/hihi:latest
