name: Checkout Service CI
on:
  push:
    branches:
      - master
    paths:
      - services/checkout/*
  pull_request:
    branches:
      - "*"
    paths:
      - services/checkout/*
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check docker
        run: |
          echo hihi;
          which docker;
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew clean && ./gradlew test

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80
