name: Local deploy CI
on:
  push:
    branches:
      - main
    paths:
      - deploys/**
  pull_request:
    branches:
      - "*"
    paths:
      - deploys/**

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  build:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout-code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Start all services
        id: up
        run: |
          docker compose -f deploys/docker-compose.yaml up -d

      - name: Stop all services
        id: down
        run: |
          docker compose -f deploys/docker-compose.yaml down
